version: '3.4'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:?err}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:?err}
    ports:
      - "${PGADMIN_PORT:-2345}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  pgadmin:
    driver: local
  postgres:
    driver: local

